export enum GEAR_STATS {
    NO_STAT = 0,
    ATTACK_FLAT,
    ATTACK_PERCENT,
    DEFENSE_FLAT,
    DEFENSE_PERCENT,
    HEALTH_FLAT,
    HEALTH_PERCENT,
    SPEED,
    CRITRATE,
    CRITDMG,
    EFFECTIVENESS,
    EFFRES
}